### ISSUE TITLE
Number Game

### ISSUE THREAD

**Issue by sonanshi-0209** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#1]
Q1. Harshit and Aditya are playing a number game. They possess a list of n integers in arr stored in strictly increasing order.
Harshit has to follow these steps
Start from left and move towards right by removing the first and every 3rd consecutive number until he reaches the end.
Repeat the previous step again, but this time move from right to left, remove the rightmost number and every 3rd number from the remaining numbers.
He has to keep repeating the steps again, alternating left to right and right to left, until two numbers remain.
Now Aditya has to guess the last two remaining numbers in sorted order. Help him win this game against Harshit.
Example-
Input =[2,6,9,10,13,16,19]
Step 1 =[2,6,9,10,13,16,19]
step-2=[6,9,13,16]
ans=9,13

**Comment by hitensam** [comment]
Hi,

Please assign this issue to me.

**Comment by karishma-2020** [comment]
please assign it to me

**Comment by hitensam** [comment]
#19 Please check!!

**Comment by jain-shreyaa-1808** [comment]
@sonanshi-0209 assign this issue to me I can solve it in best time and space complexity

**Comment by BhavyaDevani** [comment]
@sonanshi-0209 pls assign this issue to me

**Comment by Akansha3001** [comment]
Please assign this issue to me
