### ISSUE TITLE
Balanced parenthesis

### ISSUE THREAD

**Issue by sonanshi-0209** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#10]
Given an expression with only ‘}’ and ‘{‘. The expression may not be balanced. Find minimum number of bracket reversals to make the expression balanced.
Examples: 
Input:  exp = "}{"
Output: 2
We need to change '}' to '{' and '{' to
'}' so that the expression becomes balanced, 
the balanced expression is '{}'

**Comment by Namya13Jain** [comment]
I want to commit its code in Cpp

**Comment by aditi1042003** [comment]
@Parul-Mann  i want to contribute to this code

**Comment by Shreyg-27** [comment]
Hi ! 
Can this issue be assigned to me @Parul-Mann ? 
I will submit the solution in python

**Comment by Smita-Maurya** [comment]
@Parul-Mann please assign this issue to me .I want to contribute to this code in c++ language .

**Comment by jain-shreyaa-1808** [comment]
@sonanshi-0209 @Parul-Mann assign this issue to me I can solve it in best time and space complexity

**Comment by Monachaudhary** [comment]
Kindly assign this issue to me.

**Comment by gh4abhi** [comment]
Can you assign this issue to me.

**Comment by KanikaRaheja** [comment]
Hey!! I would like to contribute this code in java. Please assign me this issue.

**Comment by Mansi8874** [comment]
@sonanshi-0209 Please assign this issue to me!

**Comment by BhavyaDevani** [comment]
@sonanshi-0209 @Parul-Mann pls assign this issue to me
