### ISSUE TITLE
Find Players With Zero or One Losses

### ISSUE THREAD

**Issue by gh4abhi** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#102]
You are given an integer array matches where matches[i] = [winneri, loseri] indicates that the player winneri defeated player loseri in a match.

Return a list answer of size 2 where:

answer[0] is a list of all players that have not lost any matches.
answer[1] is a list of all players that have lost exactly one match.
The values in the two lists should be returned in increasing order.

**Comment by gh4abhi** [comment]
Please assign this issue to me.

**Comment by BhavyaDevani** [comment]
@Parul-Mann pls assign this to me
