### ISSUE TITLE
Swap Alternate

### ISSUE THREAD

**Issue by garimapahwa** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#105]
Please assign me this issue

**Comment by gh4abhi** [comment]
Please assign this issue to me.

**Comment by 0xDVC** [comment]
Please could you assign this issue to me? @Parul-Mann

**Comment by Monachaudhary** [comment]
Kindly assign this issue to me

**Comment by KanchanBora** [comment]
Given an array Arr[] of size N. You need to swap every pair of alternate elements in the array.

@gdsc-igdtuw @Parul-Mann Please assign this issue to me.

**Comment by KanchanBora** [comment]
@gdsc-igdtuw @Parul-Mann Please assign the issue to me.

**Comment by Akansha3001** [comment]
Please assign this issue to me
