### ISSUE TITLE
Reverse linked list

### ISSUE THREAD

**Issue by sonanshi-0209** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#11]
Given a pointer to the head node of a linked list, the task is to reverse the linked list. We need to reverse the list by changing the links between nodes.
Example: Input: Head of following linked list 
1->2->3->4->NULL 
Output: Linked list should be changed to, 
4->3->2->1->NULL

**Comment by aishvi-g** [comment]
@Parul-Mann pls assign me this issue

**Comment by tan1106** [comment]
Please assign this issue to me

**Comment by meghaaroraa** [comment]
@Parul-Mann please assign this issue to me

**Comment by saumyabharti294** [comment]
@Parul-Mann please assign this issue to me!

**Comment by Mansi8874** [comment]
@Parul-Mann Please assign this issue to me

**Comment by Smita-Maurya** [comment]
@Parul-Mann please assign this to me

**Comment by Smita-Maurya** [comment]
@Parul-Mann  please assign this issue to me.

**Comment by Sheetal-05** [comment]
@Parul-Mann 
Please assign this issue to me.

**Comment by jain-shreyaa-1808** [comment]
@sonanshi-0209  @Parul-Mann assign this issue to me I can solve it in best time and space complexity

**Comment by gh4abhi** [comment]
Please assign this to me.

**Comment by Neetika146** [comment]
@sonanshi-0209 @Parul-Mann please assign this issue to me

**Comment by AyushiRwt20** [comment]
@sonanshi-0209 please assign this to me

**Comment by sakshhhhhhi** [comment]
@sonanshi-0209 please assign me this issue

**Comment by liza0012** [comment]
Please assign me this issue @sonanshi-0209

**Comment by BhavyaDevani** [comment]
@sonanshi-0209 @Parul-Mann pls assign this issue to me

**Comment by ghost** [comment]
pleae assign this issue to me @Parul-Mann @gdsc-igdtuw
