### ISSUE TITLE
Longest Palindromic Substring 

### ISSUE THREAD

**Issue by 0xDVC** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#110]
Given a string s, you are to return the longest palindromic substring in s.

@Parul-Mann Please could you assign to me this issue

**Comment by gh4abhi** [comment]
Please assign this to me I will do it in C++.

**Comment by BhavyaDevani** [comment]
@Parul-Mann pls assign this issue to me

**Comment by Drishtianand19** [comment]
please assign this to me.

**Comment by liza0012** [comment]
@Parul-Mann @gdsc-igdtuw Please assign this to me

**Comment by Monachaudhary** [comment]
Kindly assign this issue to me

**Comment by Akansha3001** [comment]
Please assign this issue to me
