### ISSUE TITLE
Divide Players Into Teams of Equal Skill

### ISSUE THREAD

**Issue by gh4abhi** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#117]
You are given a positive integer array skill of even length n where skill[i] denotes the skill of the ith player. Divide the players into n / 2 teams of size 2 such that the total skill of each team is equal.

The chemistry of a team is equal to the product of the skills of the players on that team.

Return the sum of the chemistry of all the teams, or return -1 if there is no way to divide the players into teams such that the total skill of each team is equal.

**Comment by gh4abhi** [comment]
Please assign this issue to me.

**Comment by liza0012** [comment]
@Parul-Mann @gdsc-igdtuw Please assign this to me

**Comment by AarnaSinghal** [comment]
@Parul-Mann please assign this issue to me

**Comment by Monachaudhary** [comment]
Kindly assign this issue to me
