### ISSUE TITLE
Median of an array

### ISSUE THREAD

**Issue by sonanshi-0209** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#12]
Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays. Note that the overall run time complexity should be O(log (m+n))
 
Example:
 
Input:

nums1 = [1,3] 
nums2 = [2,4]
 
Output:
2.50000
 
Explanation:
Merged array = [1,2,3,4]
Median = (2+3)/2 = 2.5

**Comment by karishma-2020** [comment]
hello
Kindly assign me this issue .
I can solve this in best time and space complexity.

**Comment by karishma-2020** [comment]
@Parul-Mann 
hello
Kindly assign me this issue .
I can solve this in best time and space complexity.

**Comment by shrey-a-bansal** [comment]
@Parul-Mann 
hi di, kindly assign this to me.
thank you

**Comment by jsamiksha1** [comment]
@Parul-Mann 
Hey, please assign this issue to me :)

**Comment by tan1106** [comment]
Please assign this issue to me

**Comment by jain-shreyaa-1808** [comment]
@sonanshi-0209 @Parul-Mann assign this issue to me I can solve this is best time and space complexity

**Comment by Sheetal-05** [comment]
Please, assign this issue to me.

**Comment by gh4abhi** [comment]
Please assign this issue to me.

**Comment by AyushiRwt20** [comment]
@sonanshi-0209 please assign this to me

**Comment by Monachaudhary** [comment]
Please assign this issue to me

**Comment by BhavyaDevani** [comment]
@sonanshi-0209 @Parul-Mann pls assign this issue to me

**Comment by ghost** [comment]
please assign this to me @sonanshi-0209 @gdsc-igdtuw

**Comment by Akansha3001** [comment]
Please assign this issue to me

**Comment by Tanvi0202** [comment]
@sonanshi-0209  Please assign this issue to me
