### ISSUE TITLE
Finding most occuring element in an array of integers

### ISSUE THREAD

**Issue by jyotika6221** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#121]
Please assign me this problem.

**Comment by gh4abhi** [comment]
Please assign this issue to me.

**Comment by AarnaSinghal** [comment]
please assign this me this issue

**Comment by ghost** [comment]
please assign this issue to me @jyotika6221

**Comment by Monachaudhary** [comment]
Assign this issue to me

**Comment by gh4abhi** [comment]
@jyotika6221 Please open it, I was not able to add my solution as my internal exams are going on.
