### ISSUE TITLE
Pairs with difference K 

### ISSUE THREAD

**Issue by AarnaSinghal** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#128]
You are given with an array of integers and an integer K. You have to find and print the count of all such pairs which have difference K.
Note: Take absolute difference between the elements of the array.

**Comment by AarnaSinghal** [comment]
@gdsc-igdtuw @Parul-Mann please assign this issue to me

**Comment by gh4abhi** [comment]
Please assign this issue to me.

**Comment by Monachaudhary** [comment]
Kindly assign this to me

**Comment by Monachaudhary** [comment]
#155 Pair with difference K
