### ISSUE TITLE
Minimum steps

### ISSUE THREAD

**Issue by sonanshi-0209** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#13]
Given a string str consisting only of lowercase English letters. In one move, you can select any two adjacent characters of s and swap them. Return the minimum number of moves required to make str a palindrome. A string is said to be palindrome if it remains the same on reading from both ends.
 
Example:
 
Input:
“xxyy”
 
Output:
2
 
Explanation:
Swap indices 1 and 2 -> “xyxy”
Swap indices 0 and 1 -> “yxxy”
2 moves

**Comment by jiyasahni4** [comment]
kindly assign this to me

**Comment by karishma-2020** [comment]
hello
Kindly assign me this issue .
I can solve this in best time and space complexity.

**Comment by karishma-2020** [comment]
@Parul-Mann 
hello
Kindly assign me this issue .
I can solve this in best time and space complexity.

**Comment by saumyabharti294** [comment]
@Parul-Mann please assign this issue to me!

**Comment by Sheetal-05** [comment]
@Parul-Mann Please assign this issue to me.

**Comment by jain-shreyaa-1808** [comment]
@sonanshi-0209 assign this issue to me I can solve it in best time and space complexity

**Comment by gh4abhi** [comment]
Please assign this issue to me.

**Comment by Neetika146** [comment]
please assign this to me

**Comment by AyushiRwt20** [comment]
@sonanshi-0209 please assign this to me i can solve it best time and space complexity

**Comment by BhavyaDevani** [comment]
@sonanshi-0209 pls assign this issue to me
