### ISSUE TITLE
HAPPY NUMBER

### ISSUE THREAD

**Issue by KanchanBora** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#132]
Write an algorithm to determine if a number n is happy.

The number should start with positive integer
Replace the number by the sum of the squares of its digits.
Repeat  until the number= 1 
The numbers for which process ends with 1 are happy.

@Parul-Mann @gdsc-igdtuw Please assign me this issue.

**Comment by gh4abhi** [comment]
Please assign this issue to me.

**Comment by Monachaudhary** [comment]
Kindly assign this to me.

**Comment by ssom01-github** [comment]
Please assign the issue to me
