### ISSUE TITLE
Find subsequences

### ISSUE THREAD

**Issue by sonanshi-0209** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#14]
Given a string, we have to find out all subsequences of it. A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.
Examples: 
Input : abc
Output : a, b, c, ab, bc, ac, abc

Input : aaa
Output : a, a, a, aa, aa, aa, aaa

**Comment by chinmaychahar** [comment]
@sonanshi-0209 Kindly assign this to me.

**Comment by jsamiksha1** [comment]
hey !
kindly assign this to me.

**Comment by hitensam** [comment]
Hi

Please assign it to me.

**Comment by tan1106** [comment]
Please assign this issue to me

**Comment by Monachaudhary** [comment]
Please assign it to me

**Comment by Mansi8874** [comment]
@Parul-Mann Please assign this issue to me

**Comment by jain-shreyaa-1808** [comment]
@sonanshi-0209 assign the issue to me

**Comment by gh4abhi** [comment]
Please assign this to me.

**Comment by BhavyaDevani** [comment]
@Parul-Mann pls assign this issue to me
