### ISSUE TITLE
Longest Square Streak in an Array

### ISSUE THREAD

**Issue by gh4abhi** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#143]
You are given an integer array nums. A subsequence of nums is called a square streak if:

The length of the subsequence is at least 2, and
after sorting the subsequence, each element (except the first element) is the square of the previous number.
Return the length of the longest square streak in nums, or return -1 if there is no square streak.

A subsequence is an array that can be derived from another array by deleting some or no elements without changing the order of the remaining elements.

**Comment by gh4abhi** [comment]
Please assign this issue to me.

**Comment by Monachaudhary** [comment]
Kindly assign this to me
