### ISSUE TITLE
Intersection point

### ISSUE THREAD

**Issue by sonanshi-0209** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#15]
Given two lists sorted in increasing order, create a new list representing the intersection of the two lists. The new list should be made with its own memory — the original lists should not be changed.
Note: The list elements are not necessarily distinct.
Input:
L1 = 1->2->3->4->6
L2 = 2->4->6->8
Output: 2 4 6
Explanation: For the given first two
linked list, 2, 4 and 6 are the elements
in the intersection.

**Comment by xoxo16** [comment]
pls assign this issue to me

**Comment by karishma-2020** [comment]
hello
Kindly assign me this issue .
I can solve this in best time and space complexity.

**Comment by karishma-2020** [comment]
@Parul-Mann 
hello
Kindly assign me this issue .
I can solve this in best time and space complexity.

**Comment by xoxo16** [comment]
<img width="497" alt="Intersection of Two Linked Lists" src="https://user-images.githubusercontent.com/92911893/201535862-19b70124-d9b1-420c-a2e8-b8a13d2ddd39.png">

**Comment by tan1106** [comment]
Please assign this issue to me

**Comment by jain-shreyaa-1808** [comment]
@sonanshi-0209 @Parul-Mann  please assign this issue to me

**Comment by BhavyaDevani** [comment]
@Parul-Mann pls assign this issue to me
