### ISSUE TITLE
Majority Element

### ISSUE THREAD

**Issue by sonanshi-0209** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#2]
Given an array A of N elements. Find the majority element in the array. A majority element in an array A of size N is an element that appears more than N/2 times in the array.
 
Example 1:
Input:
N = 3 
A[] = {1,2,3} 
Output:
-1
Explanation:
Since, each element in 
{1,2,3} appears only once so there 
is no majority element.

**Comment by mansi05041** [comment]
I would like to work on this Issue
for this question I will use Moore's voting Algorithm with time complexity O(n) and space complexity O(1)
Kindly assign this issue to me.

**Comment by i-am-nandiniverma** [comment]
can you assign this to me?

**Comment by jain-shreyaa-1808** [comment]
@sonanshi-0209 assign this issue to me I can solve it in best time and space complexity

**Comment by Monachaudhary** [comment]
Kindly assign this issue to me.

**Comment by Mansi8874** [comment]
@sonanshi-0209 Please assign this issue to me!

**Comment by meghaaroraa** [comment]
@sonanshi-0209 Please assign this issue to me.

**Comment by BhavyaDevani** [comment]
@sonanshi-0209 pls assign this issue to me

**Comment by ssom01-github** [comment]
kindly assign this to me

**Comment by piyushsingh2121** [comment]
Kindly assign this issue to me

**Comment by Akansha3001** [comment]
@sonanshi-0209 @Parul-Mann Please assign this issue to me
