### ISSUE TITLE
Red Blue Balls

### ISSUE THREAD

**Issue by sonanshi-0209** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#3]
Aditya is playing with red coloured and blue coloured balls each having n balls labelled 1-n  integers. He realizes by mistake he has mixed one blue ball with the red balls and lost one red ball such that there is one repeating number and one missing number in the red balls. Determine the missing and repeating numbers for aditya to sort all the balls.
You are given n and arr(numbers labeled on all red balls)

Example-
n=3
arr=[1,3,3]
missing=2
repeating=3

**Comment by Alka-12** [comment]
I'd like to work on this problem

**Comment by karishma-2020** [comment]
please assign it to me 
@sonanshi-0209

**Comment by gh4abhi** [comment]
Please assign this issue to me.

**Comment by BhavyaDevani** [comment]
@sonanshi-0209 pls assign this issue to me

**Comment by piyushsingh2121** [comment]
Kindly assign this issue to me

**Comment by Priyanka99809** [comment]
Please assign this issue to me
