### ISSUE TITLE
Maximize Expression

### ISSUE THREAD

**Issue by 072arushi** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#35]
Given two positive integers X and Y. Let’s define W such that Y AND W = W. The task is to maximize the expression X XOR Y.

Examples
Example 1 : Input: X = 11 Y = 4 Output: 15
Example 2 : Input: X = 9 and Y = 13 Output: 13

**Comment by 072arushi** [comment]
@Parul-Mann Please assign me this issue.

**Comment by Parul-Mann** [comment]
@072arushi This issue has been assigned to you.

**Comment by Monachaudhary** [comment]
Please assign this issue to me

**Comment by BhavyaDevani** [comment]
@Parul-Mann pls assign this issue to me

**Comment by ssom01-github** [comment]
please assign this to me
