### ISSUE TITLE
N_Queen problem [ Backtracking]

### ISSUE THREAD

**Issue by Nikhila-KS** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#36]
Problem-
Place N chess queens on an N×N chessboard so that no two queens attack each other.

Example : if n=4 then the following is a solution for the 4 Queen problem.
    0 1 0 0
    0 0 0 1
    1 0 0 0
    0 0 1 0 
Where 1 represents the positions in which queen is placed

**Comment by Nikhila-KS** [comment]
Hello @Parul-Mann 
Can you assign this issue to me?

**Comment by Monachaudhary** [comment]
Kindly assign this to me. I can solve it in the best time  and space complexity.

**Comment by gh4abhi** [comment]
Please assign this to me I will do it in C++17.

**Comment by Shreyg-27** [comment]
Hello @Parul-Mann. 
Can this issue be assigned to me? I will code it in Python

**Comment by AarnaSinghal** [comment]
Hello 
please assign this issue to me 
@Parul-Mann

**Comment by BhavyaDevani** [comment]
@gdsc-igdtuw @Parul-Mann pls assign this issue to me

**Comment by ssom01-github** [comment]
hello, please assign  the issue to me

**Comment by Akansha3001** [comment]
Please assign this issue to me
