### ISSUE TITLE
levelOrderTraversalOfTree

### ISSUE THREAD

**Issue by gupta-ekansh** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#37]

**Comment by tanisha12j** [comment]
@gupta-ekansh @Parul-Mann can you assign this issue to me?

**Comment by gupta-ekansh** [comment]
I was hoping this issue gets assigned to me since I raised it

**Comment by BhavyaDevani** [comment]
@gupta-ekansh @Parul-Mann pls assign this issue to me

**Comment by Drishtianand19** [comment]
can u assign this to me? @Parul-Mann

**Comment by AarnaSinghal** [comment]
please assign this issue to me @Parul-Mann
