### ISSUE TITLE
Strings anagrams

### ISSUE THREAD

**Issue by tanisha12j** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#38]

**Comment by tanisha12j** [comment]
Problem statement-given 2 strings ,check if they are anagrams of each other or not.
Example -INPUT-CAT,ACT
OUTPUT-true
Reason -Since count of every letter of both the string are equal

**Comment by tanisha12j** [comment]
@Parul-Mann can you assign this issue to me ?

**Comment by gh4abhi** [comment]
Please assign this to me.

**Comment by Monachaudhary** [comment]
Kindly assign this to me. I have best approach to do this

**Comment by BhavyaDevani** [comment]
@gdsc-igdtuw @Parul-Mann pls assign this issue to me

**Comment by 0xDVC** [comment]
@Parul-Mann please could you assign this issue to me as well?

**Comment by ssom01-github** [comment]
please assign this to me

**Comment by KanchanBora** [comment]
@Parul-Mann please assign this issue to me.
