### ISSUE TITLE
Maximum subarray sum

### ISSUE THREAD

**Issue by tanisha12j** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#39]

**Comment by tanisha12j** [comment]
Problem statement -Given an integer array ,find contiguous array which has largest sum and return its sum and subarray .
Input- [-2,1,-3,4,,-1,2,,1,-5,4]
Output-6
Explanation-[4,-1,2,1] has largest sum 6

**Comment by tanisha12j** [comment]
@Parul-Mann can you assign this issue to me ?

**Comment by gh4abhi** [comment]
Please assign this to me.

**Comment by Neetika146** [comment]
@Parul-Mann please assign this to me

**Comment by GargNikitaa** [comment]
@Parul-Mann Kindly assign this to me

**Comment by BhavyaDevani** [comment]
@gdsc-igdtuw @Parul-Mann pls assign this issue to me

**Comment by KanchanBora** [comment]
@gdsc-igdtuw @Parul-Mann Please assign this issue to me.
