### ISSUE TITLE
Palindromic String

### ISSUE THREAD

**Issue by sonanshi-0209** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#4]
Given integers X and Y, generate a palindrome of length X consisting of lowercase English alphabets such that the number of distinct characters in the palindrome is exactly Y.
If it is impossible to do so, print -1 instead.

Example:
Input:
1 1
2 1
3 3
4 2

Output:
z
aa
-1
xyyx

**Comment by Nitya-Pasrija** [comment]
Hey @sonanshi-0209  @Parul-Mann 
Can you assign this to me?

**Comment by Shreyg-27** [comment]
Hey @sonanshi-0209 @Parul-Mann Can this issue be assigned to me? I can write the code solution in Python

**Comment by gh4abhi** [comment]
Can you please assign this issue to me.

**Comment by BhavyaDevani** [comment]
@sonanshi-0209 pls assign this issue to me

**Comment by ssom01-github** [comment]
please assign this to me

**Comment by Akansha3001** [comment]
Please assign this issue to me

**Comment by Priyanka99809** [comment]
Please assign this issue to me
