### ISSUE TITLE
Power set

### ISSUE THREAD

**Issue by tanisha12j** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#40]

**Comment by tanisha12j** [comment]
Problem Statement:Given a string, find all the possible subsequences of the string.
Example :
Input: str = "abc"
Output: a ab abc ac b bc c
Explanation: Printing all the 7 subsequence for the string "abc".

**Comment by tanisha12j** [comment]
@gdsc-igdtuw @Parul-Mann can you assign this issue to me ?

**Comment by gh4abhi** [comment]
Please assign this to me.

**Comment by AyushiRwt20** [comment]
@Parul-Mann @gdsc-igdtuw please assign this to me

**Comment by BhavyaDevani** [comment]
@Parul-Mann @gdsc-igdtuw pls assign this issue to me

**Comment by Monachaudhary** [comment]
Kindly assign this to me
