### ISSUE TITLE
Top View of Binary Tree

### ISSUE THREAD

**Issue by gh4abhi** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#41]
Given below is a binary tree. The task is to print the top view of binary tree. Top view of a binary tree is the set of nodes visible when the tree is viewed from the top. For the given below tree

![image](https://user-images.githubusercontent.com/63967165/202860134-70726053-d3e9-4592-b5df-b36d77aafe46.png)

Top view will be: 4 2 1 3 7

**Comment by gh4abhi** [comment]
Please assign this issue to me.

**Comment by gh4abhi** [comment]
@gdsc-igdtuw @Parul-Mann

**Comment by GargNikitaa** [comment]
@Parul-Mann Kindly assign this issue to me

**Comment by BhavyaDevani** [comment]
@gdsc-igdtuw @Parul-Mann pls assign this issue to me
