### ISSUE TITLE
Bottom View of Binary Tree

### ISSUE THREAD

**Issue by gh4abhi** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#49]
Given a binary tree, print the bottom view from left to right.
A node is included in bottom view if it can be seen when we look at the tree from bottom.

![image](https://user-images.githubusercontent.com/63967165/202911461-73d03501-6865-4164-bac7-1b9a41d792dc.png)

Bottom view will be: 4 2 6 3 7

**Comment by gh4abhi** [comment]
Please assign this issue to me.

**Comment by GargNikitaa** [comment]
@Parul-Mann Kindly assign this issue to me

**Comment by BhavyaDevani** [comment]
@gdsc-igdtuw @Parul-Mann pls assign this issue to me
