### ISSUE TITLE
Search the matrix

### ISSUE THREAD

**Issue by sonanshi-0209** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#5]
Write an efficient algorithm that searches for a value target in an m x n integer matrix matrix. This matrix has the following properties:
Integers in each row are sorted from left to right.
The first integer of each row is greater than the last integer of the previous row.
Input: matrix = [[1,3,5,7],[10,11,16,20],[23,30,34,60]], target = 3
Output: true

**Comment by chinmaychahar** [comment]
Kindly assign this to me.

**Comment by RidhiChhajer** [comment]
I solved the question yesterday, can this be assigned to me?

**Comment by jsamiksha1** [comment]
Hey, I would like to give its solution. Kindly assign this to me

**Comment by Sheetal-05** [comment]
Please assign this issue to me.

**Comment by jain-shreyaa-1808** [comment]
@sonanshi-0209 assign this issue to me I can solve it in best time and space complexity

**Comment by Monachaudhary** [comment]
Kindly assign this issue to me. I've best approach to do this

**Comment by gh4abhi** [comment]
Please assign this issue to me.

**Comment by Mansi8874** [comment]
@sonanshi-0209 Please assign this issue to me!

**Comment by BhavyaDevani** [comment]
@sonanshi-0209 pls assign this issue to me

**Comment by ssom01-github** [comment]
please assign the issue to me, I can solve it in best time complexity

**Comment by piyushsingh2121** [comment]
Kindly assign this to me. I can solve this question efficiently
