### ISSUE TITLE
Left View of Binary Tree

### ISSUE THREAD

**Issue by gh4abhi** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#50]
Given a Binary Tree, print Left view of it. Left view of a Binary Tree is set of nodes visible when tree is visited from Left side. The task is to complete the function leftView(), which accepts root of the tree as argument.

![image](https://user-images.githubusercontent.com/63967165/202911585-389e7ad1-5fc4-4beb-9059-72a794b093c2.png)

Left View of the tree : 1 2 4

**Comment by gh4abhi** [comment]
Please assign this issue to me.

**Comment by Mansi8874** [comment]
Please assign this issue to me!

**Comment by GargNikitaa** [comment]
@Parul-Mann Kindly assign this issue to me

**Comment by BhavyaDevani** [comment]
@gdsc-igdtuw @Parul-Mann pls assign this issue to me
