### ISSUE TITLE
Vertical Order Traversal of a Binary Tree

### ISSUE THREAD

**Issue by gh4abhi** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#51]
Given the root of a binary tree, calculate the vertical order traversal of the binary tree.

For each node at position (row, col), its left and right children will be at positions (row + 1, col - 1) and (row + 1, col + 1) respectively. The root of the tree is at (0, 0).

The vertical order traversal of a binary tree is a list of top-to-bottom orderings for each column index starting from the leftmost column and ending on the rightmost column. There may be multiple nodes in the same row and same column. In such a case, sort these nodes by their values.

Return the vertical order traversal of the binary tree.

![image](https://user-images.githubusercontent.com/63967165/202911716-736d986d-7d28-46dc-87a4-b69ab58aa8f1.png)

Vertical order traversal is : [[4],[2],[1,5,6],[3],[7]]

**Comment by gh4abhi** [comment]
Please assign this issue to me.

**Comment by BhavyaDevani** [comment]
@gdsc-igdtuw pls assign this issue to me
