### ISSUE TITLE
Max width of a Binary Tree

### ISSUE THREAD

**Issue by gh4abhi** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#52]
Given the root of a binary tree, return the maximum width of the given tree.

The maximum width of a tree is the maximum width among all levels.

The width of one level is defined as the length between the end-nodes (the leftmost and rightmost non-null nodes), where the null nodes between the end-nodes that would be present in a complete binary tree extending down to that level are also counted into the length calculation.

![image](https://user-images.githubusercontent.com/63967165/202913300-9b1b838a-0e02-4435-8eec-415606e272ae.png)

Output: 4

**Comment by gh4abhi** [comment]
Please assign this issue to me.

**Comment by mad-alpha** [comment]
Please assign this issue to me @gdsc-igdtuw @Parul-Mann @gh4abhi

**Comment by mad-alpha** [comment]
@gdsc-igdtuw @Parul-Mann I have raised a [PR](https://github.com/GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation/pull/74) for this issue.
Please review this.

**Comment by liza0012** [comment]
Please assign this issue to me @gdsc-igdtuw @Parul-Mann

**Comment by GargNikitaa** [comment]
@Parul-Mann Kindly assign this issue to me

**Comment by BhavyaDevani** [comment]
@gdsc-igdtuw @Parul-Mann pls assign this issue to me

**Comment by jyotika6221** [comment]
@gdsc-igdtuw @Parul-Mann pls assign this issue to me
