### ISSUE TITLE
Kth Largest Element in an Array

### ISSUE THREAD

**Issue by gh4abhi** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#57]
Given an integer array nums and an integer k, return the kth largest element in the array.

Note that it is the kth largest element in the sorted order, not the kth distinct element.

You must solve it in O(n) time complexity.

**Comment by gh4abhi** [comment]
Please assign this issue to me.

**Comment by mad-alpha** [comment]
Please assign this issue to me @gdsc-igdtuw @Parul-Mann

**Comment by AyushiRwt20** [comment]
@gh4abhi please assign this issue to me

**Comment by Monachaudhary** [comment]
Kindly assign this issue to me.

**Comment by mad-alpha** [comment]
@gdsc-igdtuw @Parul-Mann  I have raised a [PR](https://github.com/GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation/pull/72) for this issue. 
Please review this.

**Comment by AyushiRwt20** [comment]
@Parul-Mann please review the PR which i have issued related to this topic

**Comment by GargNikitaa** [comment]
Kindly assign this issue to me

**Comment by BhavyaDevani** [comment]
@gdsc-igdtuw pls assign this issue to me

**Comment by ssom01-github** [comment]
please assign this issue to me

**Comment by piyushsingh2121** [comment]
Kindly assign this issue to me. I will solve this in best time complexity.

**Comment by jyotika6221** [comment]
@gdsc-igdtuw @Parul-Mann  pls assign this issue to me
