### ISSUE TITLE
Spiral print

### ISSUE THREAD

**Issue by garimapahwa** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#58]
Please assign me this code  @gdsc-igdtuw

**Comment by Pratikshathisside** [comment]
please assign me this @gdsc-igdtuw

**Comment by mad-alpha** [comment]
Please assign this issue to me @gdsc-igdtuw @Parul-Mann

**Comment by mad-alpha** [comment]
@gdsc-igdtuw @Parul-Mann I have raised a [PR](https://github.com/GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation/pull/75) for this issue.
Please review this.

**Comment by liza0012** [comment]
please assign this issue to me

**Comment by jiyasahni4** [comment]
pls assign this to me

**Comment by GargNikitaa** [comment]
Kindly assign this issue to me

**Comment by BhavyaDevani** [comment]
@gdsc-igdtuw pls assign this issue to me
