### ISSUE TITLE
Maximum Sum Combinations

### ISSUE THREAD

**Issue by gh4abhi** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#59]
Given two equally sized 1-D arrays A, B containing N integers each.

A sum combination is made by adding one element from array A and another element of array B.

Return the maximum C valid sum combinations from all the possible sum combinations.

**Comment by gh4abhi** [comment]
Please assign this issue to me.

**Comment by mad-alpha** [comment]
Please assign this issue to me @gdsc-igdtuw @Parul-Mann

**Comment by Monachaudhary** [comment]
Kindly assign this issue to me. I'll write an efficient algorithm for this.

**Comment by BhavyaDevani** [comment]
@gdsc-igdtuw pls assign this issue to me
