### ISSUE TITLE
Min operations to modify the string

### ISSUE THREAD

**Issue by sonanshi-0209** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#6]
Given a string S1 of length N consisting of lowercase English alphabet letters. You are allowed to perform the following operation on the string S1 any number of times:
Select a non-empty subsequence X of the array [1,2,3,…,N] and any lowercase English alphabet α.
Change Ai to α for all i∈X.
Find the minimum number of operations required to convert S1 into a given string S2 of length N consisting of lowercase English alphabet letters.
 
Example:
Input:
3
aaa
bab
4
abcd
aaab
 
Output:
2
1
2

**Comment by karishma-2020** [comment]
hello
Kindly assign me this issue .
I can solve this in best time and space complexity.

**Comment by Nitya-Pasrija** [comment]
Hey @sonanshi-0209 
Can you assign this to me?

**Comment by jain-shreyaa-1808** [comment]
@sonanshi-0209 please assign this issue to me I want to work upon this issue

**Comment by Monachaudhary** [comment]
Please assign this issue to me. I can give the best approach to do this

**Comment by BhavyaDevani** [comment]
@sonanshi-0209 pls assign this issue to me

**Comment by ssom01-github** [comment]
please assign this to me

**Comment by Priyanka99809** [comment]
Please assign this issue to me
