### ISSUE TITLE
Kadane' algorithm

### ISSUE THREAD

**Issue by SonaVarshney** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#66]
Given an array arr[] of size N. The task is to find the sum of the contiguous subarray within a arr[] with the largest sum. 
pls assign me this issue.

**Comment by gh4abhi** [comment]
Please assign this to me.

**Comment by SonaVarshney** [comment]
@gdsc-igdtuw , made the pr , pls have a look - https://github.com/GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation/pull/79#issue-1463183155

**Comment by BhavyaDevani** [comment]
@Parul-Mann pls assign this issue to me

**Comment by KanchanBora** [comment]
@gdsc-igdtuw @Parul-Mann Please assign the issue to me.

**Comment by Monachaudhary** [comment]
Kindly assign this issue to me
