### ISSUE TITLE
Rotate the image

### ISSUE THREAD

**Issue by sonanshi-0209** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#7]
Given a square matrix, turn it by 90 degrees in an anti-clockwise direction without using any extra space
Examples: 
Input:
Matrix:    1  2  3
               4  5  6
               7  8  9
Output:  3  6  9 
               2  5  8 
               1  4  7

**Comment by RidhiChhajer** [comment]
pls assign this to me

**Comment by jsamiksha1** [comment]
hey, pls assign this to me

**Comment by Sheetal-05** [comment]
Please assign this issue to me.

**Comment by jiyasahni4** [comment]
pls assign this to me

**Comment by RidhiChhajer** [comment]
Ive already sent a pr for this question :')

**Comment by gh4abhi** [comment]
Please assign this to me.

**Comment by BhavyaDevani** [comment]
@sonanshi-0209 pls assign this issue to me

**Comment by Akansha3001** [comment]
please assign this issue to me

**Comment by Priyanka99809** [comment]
Please assign this issue to me
