### ISSUE TITLE
Word Search

### ISSUE THREAD

**Issue by gh4abhi** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#76]
Given an m x n grid of characters board and a string word, return true if word exists in the grid.

The word can be constructed from letters of sequentially adjacent cells, where adjacent cells are horizontally or vertically neighboring. The same letter cell may not be used more than once.

**Comment by gh4abhi** [comment]
Please assign this issue to me @gdsc-igdtuw @Parul-Mann

**Comment by liza0012** [comment]
Please assign this issue to me

**Comment by Monachaudhary** [comment]
Kindly assign this to me.

**Comment by BhavyaDevani** [comment]
@Parul-Mann pls assign this issue to me

**Comment by piyushsingh2121** [comment]
Kindly assign this issue to me

**Comment by liza0012** [comment]
@Parul-Mann @gdsc-igdtuw I've raised a PR please review
