### ISSUE TITLE
Best Time to Buy and Sell Stock

### ISSUE THREAD

**Issue by gh4abhi** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#78]
You are given an array prices where prices[i] is the price of a given stock on the ith day.

You want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock.

Return the maximum profit you can achieve from this transaction. If you cannot achieve any profit, return 0.

**Comment by gh4abhi** [comment]
Please assign this issue to me @gdsc-igdtuw @Parul-Mann

**Comment by bh-g** [comment]
Please assign this issue to me @gdsc-igdtuw @Parul-Mann

**Comment by ghost** [comment]
Please assign this to me @Parul-Mann
