### ISSUE TITLE
Smallest missing positive

### ISSUE THREAD

**Issue by sonanshi-0209** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#8]
Given an unsorted integer array nums, return the smallest missing positive integer.
You must implement an algorithm that runs in O(n) time and uses constant extra space.
Input: nums = [3,4,-1,1]
Output: 2
Explanation: 1 is in the array but 2 is missing.

**Comment by chinmaychahar** [comment]
I'd like to contribute to this issue. Kindly assign

**Comment by karishma-2020** [comment]
hello
Kindly assign me this issue .
I can solve this in best time and space complexity.

**Comment by karishma-2020** [comment]
@Parul-Mann 
hello
Kindly assign me this issue .
I can solve this in best time and space complexity.

**Comment by jsamiksha1** [comment]
hey , could you please assign this issue to me

**Comment by jain-shreyaa-1808** [comment]
@sonanshi-0209 @Parul-Mann assign this issue to me I can solve it in best time and space complexity

**Comment by Monachaudhary** [comment]
Please assign it to me. I have the best approach to do this. 
 I can solve this in the best time and space complexity

**Comment by piyushsingh2121** [comment]
Kindly assign this to me

**Comment by Neetika146** [comment]
please assign this to me.

**Comment by BhavyaDevani** [comment]
@sonanshi-0209 pls assign this issue to me

**Comment by Tanvi0202** [comment]
@sonanshi-0209 Please this issue to me
