### ISSUE TITLE
Remove Duplicates from Sorted Array 

### ISSUE THREAD

**Issue by deeksha04-alt** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#80]
You are given a sorted array in increasing order, you are required to remove the duplicates [in-place] such that each unique element appears only once. The relative order of the elements should be kept the same.

Return N- no of unique elements  after placing the final resultant unique elements in the first n slots of input array.

Constraints: You must do this by modifying the input array [in-place with O(1) extra memory.

Kindly assign me this issue @gdsc-igdtuw @Parul-Mann

**Comment by gh4abhi** [comment]
Please assign this to me. I will do it in C++.

**Comment by Monachaudhary** [comment]
Kindly assign this to me

**Comment by BhavyaDevani** [comment]
@Parul-Mann pls assign this issue to me

**Comment by parmesh-bhatt** [comment]
Please assign this to me. I will do it in just 4 lines of code.

**Comment by ghost** [comment]
please assign this issue to me @Parul-Mann @gdsc-igdtuw

**Comment by KanchanBora** [comment]
@Parul-Mann @gdsc-igdtuw Please assign this issue to me.

**Comment by Akansha3001** [comment]
Please assign this issue to me

**Comment by ssom01-github** [comment]
Please assign the issue to me
