### ISSUE TITLE
Maximum twin sum in a Linked List

### ISSUE THREAD

**Issue by deeksha04-alt** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#81]
You are given a linked list of size N,
 where n is even, the i-th node (0-indexed) of the linked list is known as the twin of the (n-1-i)th node, if 0 <= i <= (n / 2) - 1.

For example, if n = 4, then node 0 is the twin of node 3, and node 1 is the twin of node 2. These are the only nodes with twins for n = 4.
The twin sum is defined as the sum of a node and its twin.

Given the head of a linked list with even length, return the maximum twin sum of the linked list.

**Comment by deeksha04-alt** [comment]
kindly assign me the above issue @gdsc-igdtuw @Parul-Mann

**Comment by gh4abhi** [comment]
Please assign this to me.

**Comment by bh-g** [comment]
Please assign this issue to me @Parul-Mann @gdsc-igdtuw

**Comment by BhavyaDevani** [comment]
@Parul-Mann pls assign this issue to me

**Comment by jyotika6221** [comment]
@Parul-Mann kindly assign this issue to me
