### ISSUE TITLE
Maximum Deletions on a String

### ISSUE THREAD

**Issue by gh4abhi** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#86]
You are given a string s consisting of only lowercase English letters. In one operation, you can:

1. Delete the entire string s, or
2. Delete the first i letters of s if the first i letters of s are equal to the following i letters in s, for any i in the range 1 <= i <= s.length / 2.
For example, if s = "ababc", then in one operation, you could delete the first two letters of s to get "abc", since the first two letters of s and the following two letters of s are both equal to "ab".

Return the maximum number of operations needed to delete all of s

**Comment by gh4abhi** [comment]
Please assign this issue to me.

**Comment by liza0012** [comment]
Please assign this issue to me @gdsc-igdtuw @Parul-Mann

**Comment by Monachaudhary** [comment]
Kindly assign this to me

**Comment by BhavyaDevani** [comment]
@Parul-Mann pls assign this issue to me
