### ISSUE TITLE
Is tree mirror?

### ISSUE THREAD

**Issue by sonanshi-0209** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#9]
Given the root of a binary tree, check whether it is a mirror of itself (i.e., symmetric around its center).
Input: root = [1,2,2,3,4,4,3]
Output: true
Constraints:
The number of nodes in the tree is in the range [1, 1000].
-100 <= Node.val <= 100

**Comment by i-am-nandiniverma** [comment]
please assign me this issue
(Nandini Verma CSE 3)

**Comment by i-am-nandiniverma** [comment]
solution added

**Comment by Shreyg-27** [comment]
Hey @sonanshi-0209 @Parul-Mann 
Can this issue be assigned to me? I will write the code in python.

**Comment by Mansi8874** [comment]
@Parul-Mann Please assign this issue to me!

**Comment by gh4abhi** [comment]
Please assign this issue to me.

**Comment by BhavyaDevani** [comment]
@sonanshi-0209 @Parul-Mann pls assign this issue to me
