### ISSUE TITLE
Find the Pivot Integer

### ISSUE THREAD

**Issue by gh4abhi** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#94]
Given a positive integer n, find the pivot integer x such that:

The sum of all elements between 1 and x inclusively equals the sum of all elements between x and n inclusively.
Return the pivot integer x. If no such integer exists, return -1. It is guaranteed that there will be at most one pivot index for the given input

**Comment by gh4abhi** [comment]
Please assign this issue to me.

**Comment by Monachaudhary** [comment]
Kindly assign this issue to me.

**Comment by BhavyaDevani** [comment]
@Parul-Mann pls assign this to me

**Comment by piyushsingh2121** [comment]
Kindly assign this to me. I have best approach to do this

**Comment by ssom01-github** [comment]
please assign this issue to me
