### ISSUE TITLE
Append Characters to String to Make Subsequence

### ISSUE THREAD

**Issue by gh4abhi** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#95]
You are given two strings s and t consisting of only lowercase English letters.

Return the minimum number of characters that need to be appended to the end of s so that t becomes a subsequence of s.

A subsequence is a string that can be derived from another string by deleting some or no characters without changing the order of the remaining characters.

**Comment by gh4abhi** [comment]
Please assign this issue to me.

**Comment by Monachaudhary** [comment]
Kindly assign it to me.

**Comment by BhavyaDevani** [comment]
@Parul-Mann pls assign this to me

**Comment by 0xDVC** [comment]
@Parul-Mann  I would love to be assigned to this issue
