### ISSUE TITLE
Remove Nodes From Linked List

### ISSUE THREAD

**Issue by gh4abhi** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#96]
You are given the head of a linked list.

Remove every node which has a node with a strictly greater value anywhere to the right side of it.

Return the head of the modified linked list.

![image](https://user-images.githubusercontent.com/63967165/204119871-98e17854-1c6b-4013-a961-cca3bf46dc07.png)

**Comment by gh4abhi** [comment]
Please assign this issue to me.

**Comment by deeksha04-alt** [comment]
Please assign this issue to me. @gdsc-igdtuw @Parul-Mann

**Comment by BhavyaDevani** [comment]
@Parul-Mann pls assign this to me

**Comment by ghost** [comment]
please assign this to me @Parul-Mann @gdsc-igdtuw
