### ISSUE TITLE
Majority element in an array

### ISSUE THREAD

**Issue by deeksha04-alt** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#97]
Given an array nums of size n, return the majority element.

The majority element is the element that appears more than ⌊n / 2⌋ times. You may assume that the majority element always exists in the array.
Kindly assign me the issue @gdsc-igdtuw @Parul-Mann

**Comment by gh4abhi** [comment]
Please assign this to me.

**Comment by Monachaudhary** [comment]
Kindly assign it to me

**Comment by BhavyaDevani** [comment]
@Parul-Mann pls assign this issue to me

**Comment by ssom01-github** [comment]
please assign the issue to me, I can solve in best possible time complexity.
