### ISSUE TITLE
First smallest missing positive integer

### ISSUE THREAD

**Issue by deeksha04-alt** [GDSC-IGDTUW-Autumn-of-Code-2022/dsa-foundation#98]
Given an unsorted integer array , return the smallest missing positive integer.

Constraints: TC- O(N) and uses constant extra space only

@gdsc-igdtuw @Parul-Mann  kindly assign me the issue

**Comment by gh4abhi** [comment]
Please assign this to me.

**Comment by Monachaudhary** [comment]
Kindly assign this to me.

**Comment by GargNikitaa** [comment]
@Parul-Mann Kindly assign this to me

**Comment by BhavyaDevani** [comment]
@Parul-Mann pls assign this to me

**Comment by ssom01-github** [comment]
kindly assign this to me

**Comment by BhavyaDevani** [comment]
@sonanshi-0209 I have created a PR for this issue. Kindly review it.
